# Generated by Django 5.1.3 on 2024-12-02 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_student_roll_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='payment_mode',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='enrollment_status',
            field=models.CharField(choices=[('payment_pending', 'Payment Pending'), ('paid', 'Paid')], default='payment_pending', max_length=20),
        ),
        migrations.AddField(
            model_name='installment',
            name='payment_mode',
            field=models.CharField(choices=[('pay_in_full', 'Pay in Full'), ('installments', 'Installments')], default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='installment',
            name='amount_paid',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
