# Generated by Django 5.1.3 on 2024-12-03 13:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_enrollment_payment_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='installment',
            name='transaction_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank')], default='cash', max_length=10),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing')], default='outgoing', max_length=10)),
                ('transaction_method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank')], default='cash', max_length=10)),
                ('amount', models.FloatField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
