# Generated by Django 5.1.3 on 2024-12-05 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_enrollment_created_at_installment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('jazz cash', 'Jazz Cash')], default='cash', max_length=10),
        ),
    ]
